options:
  openstack-release:
    type: string
    default: mitaka
    description: OpenStack release to use for configuration of remote compute node.
  remote-user:
    type: string
    default:
    description: Username used to access remote compute nodes.
  remote-key:
    type: string
    default:
    description: SSH key to use to access remote compute nodes.
  remote-repos:
    type: string
    default:
    description: Comma separated list of RPM repositorys of OpenStack packages to deploy to remote compute nodes.
  remote-hosts:
    type: string
    default:
    description: Remote compute node hosts to manager; space delimited.
  remote-password:
    type: string
    default:
    description: sudo password on remote compute node (NOT recommended). Use ssh key instead.
  rabbit-user:
    default: nova
    type: string
    description: Username used to access rabbitmq queue
  rabbit-vhost:
    default: openstack
    type: string
    description: Rabbitmq vhost
  debug:
    type: boolean
    default: false
    description: Enabled debug level logging
  verbose:
    type: boolean
    default: false
    description: Enabled verbose level logging
  use-syslog:
    type: boolean
    default: False
    description: |
      By default, all services will log into their corresponding log files.
      Setting this to True will force all services to log to the syslog.
  instances-path:
    type: string
    default:
    description: Instance path to use - empty means default of /var/lib/nova/instances
  config-flags:
    type: string
    default:
    description: |
      Comma-separated list of key=value config flags. These values will be
      placed in the nova.conf [DEFAULT] section.  Use with caution.
  data-port:
    type: string
    default:
    description: |
      The data port will be added to br-data and will allow usage of flat or VLAN
      network types with Neutron.
  disable-security-groups:
    type: boolean
    default: false
    description: |
      Disable neutron based security groups - setting this configuration option
      will override any settings configured via the neutron-api charm.
      .
      BE CAREFUL - this option allows you to disable all port level security within
      an OpenStack cloud.
  prevent-arp-spoofing:
    type: boolean
    default: true
    description: |
      Enable suppression of ARP responses that don't match an IP address that belongs
      to the port from which they originate.
      .
      Only supported in OpenStack Liberty or newer, which has the required minimum version
      of Open vSwitch.
  cpu-mode:
    type: string
    default:
    description: |
      Set to 'host-model' to clone the host CPU feature flags; to 
      'host-passthrough' to use the host CPU model exactly; to 'custom' to 
      use a named CPU model; to 'none' to not set any CPU model. If 
      virt_type='kvm|qemu', it will default to 'host-model', otherwise it will 
      default to 'none'.  Defaults to 'host-passthrough' for ppc64el, ppc64le
      if no value is set.
  cpu-model:
    type: string
    default:
    description: |
      Set to a named libvirt CPU model (see names listed in 
      /usr/share/libvirt/cpu_map.xml). Only has effect if cpu_mode='custom' and 
      virt_type='kvm|qemu'.
  reserved-host-memory:
    type: int
    default: 512
    description: |
      Amount of memory in MB to reserve for the host. Defaults to 512MB.

