options:
  openstack-release:
    type: string
    default: icehouse
    description: OpenStack release to use for configuration of POWER hypervisor.
  power-user:
    type: string
    default:
    description: Username used to access POWER hypervisors.
  power-key:
    type: string
    default:
    description: SSH key to use to accesss POWER hypervisors.
  power-repo:
    type: string
    default:
    description: RPM repository of OpenStack packages to deploy to POWER hypervisors.
  power-hosts:
    type: string
    default:
    description: POWER hosts to manager; space delimited.
  power-password:
    type: string
    default:
    description: sudo password on POWER hypervisor
  rabbit-user:
    default: nova
    type: string
    description: Username used to access rabbitmq queue
  rabbit-vhost:
    default: openstack
    type: string
    description: Rabbitmq vhost
  debug:
    type: boolean
    default: false
    description: Enabled debug level logging
  verbose:
    type: boolean
    default: false
    description: Enabled verbose level logging
  use-syslog:
    type: boolean
    default: False
    description: |
      By default, all services will log into their corresponding log files.
      Setting this to True will force all services to log to the syslog.
  instances-path:
    type: string
    default:
    description: Instance path to use - empty means default of /var/lib/nova/instances
  config-flags:
    type: string
    default:
    description: Comma separated list of key=value config flags to be set in nova.conf.
  data-port:
    type: string
    default:
    description: |
      The data port will be added to br-data and will allow usage of flat or VLAN
      network types with Neutron.
  disable-security-groups:
    type: boolean
    default: false
    description: |
      Disable neutron based security groups - setting this configuration option
      will override any settings configured via the neutron-api charm.
      .
      BE CAREFUL - this option allows you to disable all port level security within
      an OpenStack cloud.

